# Generated by Django 6.0.2 on 2026-02-16 10:00

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Service_id', models.AutoField(primary_key=True, serialize=False)),
                ('Service_name', models.CharField(max_length=100)),
                ('avg_service_time', models.PositiveBigIntegerField(help_text='Average service time in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('Counter_id', models.AutoField(primary_key=True, serialize=False)),
                ('Counter_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='queue_system.service')),
            ],
            options={
                'db_table': 'counters',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('priority_flag', models.BooleanField(default=False)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_wait_time', models.PositiveIntegerField(blank=True, help_text='Predicted wait time in minutes', null=True)),
                ('actual_wait_time', models.PositiveIntegerField(blank=True, help_text='Actual wait time in minutes', null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='queue_system.counter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queue_system.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('token_generated', 'Token Generated'), ('turn_approaching', 'Turn Approaching'), ('final_call', 'Final Call'), ('delay_alert', 'Delay Alert'), ('counter_changed', 'Counter Changed')], max_length=50)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='queue_system.token')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Overall service rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('waiting_satisfaction', models.PositiveIntegerField(help_text='Waiting time satisfaction (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='queue_system.token')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('queue_length', models.PositiveIntegerField()),
                ('active_counters', models.PositiveIntegerField()),
                ('waiting_count', models.PositiveIntegerField()),
                ('completed_count', models.PositiveIntegerField()),
                ('avg_service_time', models.FloatField()),
                ('max_wait_time', models.PositiveIntegerField()),
                ('min_wait_time', models.PositiveIntegerField()),
                ('peak_hour', models.BooleanField(default=False)),
                ('predicted_wait_time', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_avg_wait_time', models.PositiveIntegerField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_logs', to='queue_system.service')),
            ],
            options={
                'db_table': 'queue_logs',
                'indexes': [models.Index(fields=['timestamp'], name='queue_logs_timesta_285910_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['user'], name='tokens_user_id_0d1983_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['service'], name='tokens_service_7d35c3_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['status'], name='tokens_status_0bafa4_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['created_at'], name='tokens_created_a3c85e_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('created_at'), models.F('service'), models.F('token_number'), name='unique_token_per_service_per_day'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
    ]
