# Generated by Django 6.0.2 on 2026-02-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('collaborative_filtering', 'Collaborative Filtering')], max_length=50)),
                ('predicted_value', models.FloatField()),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(help_text='Input features used for prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='queue_system.token')),
            ],
            options={
                'db_table': 'ml_predictions',
            },
        ),
    ]
